// F O X

let fsoul = "//lnc-fox-soul-scte.tubi.video/index.m3u8";
let fseattle = "//lnc-kcpq-fox-aws.tubi.video/index.m3u8";
let fdallas = "//lnc-kdfw-fox-aws.tubi.video/index.m3u8";
let fdallas = "//lnc-kdfw-fox-aws.tubi.video/index.m3u8";
let fminneapolis = "//lnc-kmsp-fox-aws.tubi.video/index.m3u8";
let fhouston = "//lnc-kriv-fox-aws.tubi.video/index.m3u8";
let fphoenix = "//lnc-ksaz-fox-aws.tubi.video/index.m3u8";
let faustin = "//lnc-ktbc-fox-aws.tubi.video/index.m3u8";
let flosangeles = "//lnc-kttv-fox-aws.tubi.video/index.m3u8";
let fsanfrancisco = "//lnc-ktvu-fox-aws.tubi.video/index.m3u8";
let fatlanta = "//lnc-waga-fox-aws.tubi.video/index.m3u8";
let fchicago = "//lnc-wfld-fox-aws.tubi.video/index.m3u8";
let fmilwaukee = "//lnc-witi-fox-aws.tubi.video/index.m3u8";
let fdetroit = "//lnc-wjbk-fox-aws.tubi.video/index.m3u8";
let fnewyork = "//lnc-wnyw-fox-aws.tubi.video/index.m3u8";
let forlando = "//lnc-wofl-fox-aws.tubi.video/index.m3u8";
let fsacannah = "http://content.uplynk.com/channel/e56ba52a1b9d45ad8c8a033fd83fe480.m3u8";
let ftulsa = "//d3nzocdfkx2ybv.cloudfront.net/in/cmg-kokitv-hls-v3/live.m3u8";
let fmiami = "//bcsecurelivehls-i.akamaihd.net/hls/live/598043/4368278029001_1/onair/master.m3u8";
let fwashington = "//lnc-wttg-fox-aws.tubi.video/index.m3u8";
let ftampa = "//lnc-wtvt-fox-aws.tubi.video/index.m3u8";
let fphiladelphia = "//lnc-wtxf-fox-aws.tubi.video/index.m3u8";